name: .NET CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'

    # We now specify the solution file for each dotnet command
    - name: Restore dependencies
      run: dotnet restore PackageDeliver.sln

    - name: Build
      run: dotnet build PackageDeliver.sln --no-restore -c Release

    - name: Publish
      run: dotnet publish PackageDeliver.sln -c Release --no-build -o ./publish

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: PackageDeliver-Executable
        path: ./publish
