name: .NET CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # Also updated checkout to v4 for consistency

    - name: Setup .NET
      uses: actions/setup-dotnet@v4 # Also updated setup-dotnet to v4
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore -c Release

    - name: Publish
      run: dotnet publish -c Release --no-build -o ./publish

    # This is the line that was fixed
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: PackageDeliver-Executable
        path: ./publish
